version: 0.4.6

namespace: essenteil
project: essenteil

services:
  - name: web
    image: ghcr.io/markmorcos/essenteil
    port: 3000
    env:
      - name: NODE_ENV
        value: production
      - name: NEXT_PUBLIC_FIREBASE_API_KEY
        valueFrom:
          secretKeyRef:
            name: firebase-secret
            key: NEXT_PUBLIC_FIREBASE_API_KEY
      - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        valueFrom:
          secretKeyRef:
            name: firebase-secret
            key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        valueFrom:
          secretKeyRef:
            name: firebase-secret
            key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        valueFrom:
          secretKeyRef:
            name: firebase-secret
            key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        valueFrom:
          secretKeyRef:
            name: firebase-secret
            key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - name: NEXT_PUBLIC_FIREBASE_APP_ID
        valueFrom:
          secretKeyRef:
            name: firebase-secret
            key: NEXT_PUBLIC_FIREBASE_APP_ID
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: database-secret
            key: DATABASE_URL
    ingress:
      host: essenteil.de
      path: /?(.*)
      pathType: ImplementationSpecific
